language: node_js
node_js: "14"
cache:
  directories:
    - node_modules
install:
  - npm install
scripts:
  - npm run build
  - npm run test:e2e:run
notifications:
  webhooks: 
    urls:
      - https://api.netlify.com/build_hooks/61016375ffa39e0eebca9ecf
    on_success: always
    on_failure: never
    on_cancel: never
    on_error: never

