language: node_js
node_js: "14"
install:
  - npm ci
cache:
  directories:
    - "$HOME/.npm"
scripts:
  - npm run build
  - npm run test:e2e:run
deploy:
  provider: netlify
  site: 
    -env : 
      NETLIFY_SITE_ID
  auth: 
    -env:
      NETLIFY_AUTH
  edge: true
  dir: "dist"
  prod: true
  on:
    branch: main